# Generated by Django 4.0 on 2022-10-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default="2022-10-10"),
            preserve_default=False,
        ),
    ]
