# Generated by Django 4.0 on 2022-10-16 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='collection',
            new_name='category',
        ),
    ]
