# Generated by Django 4.0 on 2022-10-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='session_ID',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
