# Generated by Django 4.0 on 2022-10-19 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0005_remove_address_customer_address_user'),
        ('store', '0008_alter_order_delivered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_accounts.customer'),
        ),
    ]
