# Generated by Django 4.0 on 2022-10-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_contactus_subject_alter_contactus_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.URLField(blank=True, null=True),
        ),
    ]
