# Generated by Django 4.0 on 2022-10-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_product_active_alter_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stripe_price_id',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
