# Generated by Django 4.0 on 2022-10-14 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0002_customer_geneder_alter_customer_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='geneder',
            new_name='gender',
        ),
    ]
